### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by VibhanshuPandey** [NebulaTris/vibescape#8]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://vibescape.streamlit.app/nebulatris/vibescape/main/1_🎵_Homepage.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

![image](https://github.com/NebulaTris/vibescape/assets/111169133/ec762a7c-9050-43ab-81d2-b6e523dde4c1)

**Comment by NebulaTris** [comment]
Hi @VibhanshuPandey !👋

Thank you for notifying me regarding this 
I am aware of the situation 🙏
Would most likely try to resolve this matter in the near future.

Regards,
Shambhavi
